  n%%N%%:
    << : *default-node
    container_name: n%%N%%
    hostname: n%%N%%
    environment:
        KLEIN_ID: %%N%%
        KLEIN_PORT: 1218
        KLEIN_IP: n%%N%%
        KLEIN_MEMBERS: %%MEMBER%%